services:
    fluentd:
      build: build
      ports:
        - 12201:12201/udp
      volumes:
        - ./fluent.conf:/fluentd/etc/fluent.conf:ro,z
    vector:
      image: timberio/vector:0.42.0-debian
      #environment:
      #  VECTOR_LOG: debug
      volumes:
       - ./vector.yaml:/etc/vector/vector.yaml:ro,z

